package mocks

import (
	"bibit-test/models"

	"github.com/stretchr/testify/mock"
)

// MoviesLogSearch is an autogenerated mock type for the MoviesLogSearch type
type MoviesLogSearch struct {
	mock.Mock
}

// Search provides a mock function with given fields: models.MoviesLogSearch
func (_m *MoviesLogSearch) Search(mls *models.MoviesLogSearch) error {
	ret := _m.Called(mls)

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.MoviesLogSearch) error); ok {
		r1 = rf(mls)
	} else {
		r1 = ret.Error(1)
	}

	return r1
}
